''
'' Nord Night theme for PlantUML
''
'' Author: Jason Kuan
''
'' This program is free software: you can redistribute it and/or modify
'' it under the terms of the GNU General Public License as published by
'' the Free Software Foundation, either version 3 of the License, or
'' (at your option) any later version.
'' 
'' This program is distributed in the hope that it will be useful,
'' but WITHOUT ANY WARRANTY; without even the implied warranty of
'' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'' GNU General Public License for more details.
'' 
'' You should have received a copy of the GNU General Public License
'' along with this program.  If not, see <https://www.gnu.org/licenses/>.
!$NIGHT1 = "#2e3440"
!$NIGHT2 = "#3b4252"
!$NIGHT3 = "#434c5e"
!$BGCOLOR = "#4c566a"
!$SNOW1 = "#d8dee9"
!$SNOW2 = "#e5e9f0"
!$SNOW3 = "#eceff4"
!$FROST1 = "#8fbcbb"
!$FROST2 = "#88c0d0"
!$FROST3 = "#81a1c1"
!$FROST4 = "#5e81ac"
!$RED = "#bf616a"
!$ORANGE = "#d08770"
!$YELLOW = "#ebcb8b"
!$GREEN = "#a3be8c"
!$VIOLET = "#b48ead"

'' Lighter colors
!procedure $obj_scheme()
  FontColor $SNOW3
  BorderColor $SNOW1
  BackgroundColor $FROST3
!endprocedure

'' Darker colors
!procedure $blk_scheme()
  FontColor $SNOW3
  BorderColor $SNOW1
  BackgroundColor $FROST4
!endprocedure

<style>
  root {
    BackgroundColor $BGCOLOR
    FontColor $SNOW2
    HyperLinkColor $ORANGE
    LineColor $SNOW1
    LineThickness 1
    Margin 4
    Padding 6
    Shadowing 0.0
  }
  spot {
    spotAnnotation {
      FontColor $NIGHT1
      BackgroundColor $YELLOW
    }
    spotAbstractClass {
      FontColor $NIGHT1
      BackgroundColor $FROST1
    }
    spotClass {
      FontColor $NIGHT1
      BackgroundColor $GREEN
    }
    spotInterface {
      FontColor $NIGHT1
      BackgroundColor $VIOLET
    }
    spotEnum {
      FontColor $NIGHT1
      BackgroundColor $ORANGE
    }
    spotEntity {
      FontColor $NIGHT1
      BackgroundColor $GREEN
    }
    spotException {
      FontColor $NIGHT1
      BackgroundColor $RED
    }
    spotMetaclass {
      FontColor $NIGHT1
      BackgroundColor $SNOW1
    }
    spotProtocol {
      FontColor $NIGHT1
      BackgroundColor $SNOW2
    }
    spotStereotype {
      FontColor $NIGHT1
      BackgroundColor $VIOLET
    }
    spotStruct {
      FontColor $NIGHT1
      BackgroundColor $SNOW2
    }
  }
  ganttDiagram {
    task {
      BackGroundColor $FROST4
      LineColor $NIGHT2
      Margin 4
      Padding 6
    }
    separator {
      $obj_scheme()
    }
    milestone {
  	  FontSize 16
  	  FontStyle italic
      FontColor $SNOW3
  	  BackGroundColor $GREEN
    }
    closed {
      FontColor $VIOLET
      BackgroundColor $YELLOW
    }
  }
</style>

skinparam responseMessageBelowArrow true
hide footbox
skinparam ParticipantPadding 8
skinparam BoxPadding 8
skinparam shadowing false
skinparam RoundCorner 8

skinparam BackgroundColor $BGCOLOR
skinparam ArrowColor #eceff4
skinparam FontColor #SNOW3
skinparam SequenceLifeLineBorderColor #eceff4

' Box
skinparam SequenceBoxFontColor #eceff4
skinparam SequenceBoxBorderColor #81a1c1
skinparam SequenceBoxBackgroundColor $FROST3

' Group
skinparam SequenceGroupFontColor $SNOW3
skinparam SequenceGroupBorderColor $SNOW1
skinparam SequenceGroupBorderThickness 1
skinparam SequenceGroupBackgroundColor $FROST2
skinparam SequenceGroupBodyBackgroundColor $FROST2

' Reference'
skinparam ReferenceFontColor $SNOW3

skinparam title {
    FontColor $SNOW1
    BorderColor	$FROST1
    FontSize 20
    BorderRoundCorner 8
    BorderThickness 1
    BackgroundColor $GREEN
}

skinparam legend {
    $obj_scheme()
}

skinparam participant {
    FontColor $SNOW1
    BorderColor $FROST4
    BackgroundColor $FROST4
}

skinparam partition {
    $obj_scheme()
}

skinparam activity {
    FontColor $SNOW1
    BorderColor $SNOW3
    BackgroundColor $FROST4
    BarColor $SNOW1
	StartColor $GREEN
	EndColor $SNOW1
  	DiamondFontColor $SNOW3
  	DiamondBorderColor $SNOW1
    DiamondBackgroundColor none
}

skinparam actor {
    $obj_scheme()
}

skinparam agent {
    $obj_scheme()
}

skinparam artifact {
    $obj_scheme()
}

skinparam boundary {
    $obj_scheme()
    BackgroundColor none
}

skinparam card {
    $obj_scheme()
}

skinparam cloud {
    $obj_scheme()
    BackgroundColor none
}

skinparam collections {
    $obj_scheme()
}

skinparam component {
    $blk_scheme()
}

skinparam control {
    $obj_scheme()
    BackgroundColor none
}

skinparam database {
    $obj_scheme()
}

skinparam entity {
    $obj_scheme()
    BackgroundColor none
}

skinparam file {
    $obj_scheme()
}

skinparam folder {
    $obj_scheme()
}

skinparam frame {
    $obj_scheme()
}

skinparam hexagon {
    $obj_scheme()
}

skinparam interface {
    $obj_scheme()
    backgroundcolor $ORANGE
}

skinparam node {
    $obj_scheme()
}

skinparam package {
    $blk_scheme()
}

skinparam person {
    $obj_scheme()
    BackgroundColor none
}

skinparam queue {
    $obj_scheme()
}

skinparam rectangle {
    $blk_scheme()
}

skinparam stack {
    $obj_scheme()
    BackgroundColor none
}

skinparam storage {
    $obj_scheme()
}

skinparam usecase {
    $obj_scheme()
    BackgroundColor none
}

skinparam object {
    $blk_scheme()
}

skinparam note {
    BackgroundColor $ORANGE
    BorderColor $SNOW1
    FontColor $SNOW3
}

skinparam class {
	StereotypeFontColor $SNOW1
}

skinparam state {
    $blk_scheme()
}

